PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

DROP TABLE IF EXISTS categories;
CREATE TABLE categories (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, name VARCHAR (50));

DROP TABLE IF EXISTS courses;
CREATE TABLE courses (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, category_id INTEGER, name VARCHAR (50));

DROP TABLE IF EXISTS courses_students;
CREATE TABLE courses_students (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, course_id INTEGER, student_id INTEGER);

DROP TABLE IF EXISTS students;
CREATE TABLE students (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, name VARCHAR (50));

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;